from sqlalchemy import inspect


def test_initial_schema_contains_required_tables(session):
    required = {
        "accounts",
        "holdings",
        "trades",
        "trade_reviews",
        "discipline_rules",
        "discipline_events",
        "market_quotes",
        "market_daily_bars",
        "market_intraday_bars",
        "market_turnover_snapshots",
        "market_breadth_snapshots",
        "market_amount_snapshots",
        "industry_market_snapshots",
        "industry_constituent_snapshots",
        "industry_analysis_snapshots",
        "market_regime_snapshots",
        "concepts",
        "company_concepts",
        "industry_chains",
        "industry_chain_nodes",
        "company_chain_positions",
        "mapping_evidence",
        "market_source_logs",
        "x_watch_accounts",
        "x_watch_queries",
        "x_posts",
        "ai_analyses",
        "backtest_runs",
        "system_jobs",
        "technical_snapshots",
        "company_profiles",
        "company_financial_periods",
        "company_announcements",
        "company_valuation_snapshots",
        "company_research_evidence",
        "rule_sets",
        "rule_versions",
        "trade_plans",
        "trade_plan_checks",
        "position_snapshots",
        "trade_plan_ai_analyses",
        "plan_analysis_runs",
        "data_provider_call_logs",
        "data_quality_records",
        "data_quality_subject_heads",
        "company_research_refreshes",
        "plan_execution_events",
        "watchlist_items",
        "watchlist_revisions",
        "watchlist_transitions",
        "monitoring_events",
        "reanalysis_requests",
        "reanalysis_runs",
        "watchlist_monitor_leases",
        "plan_execution_fills",
        "industry_capital_flow_snapshots",
        "market_event_pool_snapshots",
        "candidate_discovery_runs",
        "candidate_industry_assessments",
        "discovery_candidates",
    }
    assert required == set(inspect(session.bind).get_table_names())
